import logging
import time
from copy import copy
from dataclasses import dataclass, field
from typing import Any, Protocol, Self, TypeVar, cast

import numpy as np
import torch
from torch.distributions import Categorical, Distribution

from tianshou.data import (
    Batch,
    SequenceSummaryStats,
    to_numpy,
)
from tianshou.data.buffer.base import MalformedBufferError
from tianshou.data.stats import compute_dim_to_summary_stats
from tianshou.data.types import (
    ActBatchProtocol,
    DistBatchProtocol,
    ObsBatchProtocol,
    RolloutBatchProtocol,
)

from tianshou.utils.determinism import TraceLogger
from tianshou.utils.print import DataclassPPrintMixin

log = logging.getLogger(__name__)

DEFAULT_BUFFER_MAXSIZE = int(1e4)

_TArrLike = TypeVar("_TArrLike", bound="np.ndarray | torch.Tensor | Batch | None")

TScalarArrayShape = TypeVar("TScalarArrayShape")

class CollectActionBatchProtocol(Protocol):
    """A protocol for results of computing actions from a batch of observations within a single collect step.

    All fields all have length R (the dist is a Distribution of batch size R),
    where R is the number of ready envs.
    """

    act: np.ndarray | torch.Tensor
    act_normalized: np.ndarray | torch.Tensor
    policy_entry: Batch
    dist: Distribution | None
    hidden_state: np.ndarray | torch.Tensor | Batch | None


class CollectStepBatchProtocol(RolloutBatchProtocol):
    """A batch of steps collected from a single collect step from multiple envs in parallel.

    All fields have length R (the dist is a Distribution of batch size R), where R is the number of ready envs.
    This is essentially the response of the vectorized environment to making a step
    with :class:`CollectActionBatchProtocol`.
    """

    dist: Distribution | None


class EpisodeBatchProtocol(RolloutBatchProtocol):
    """Marker interface for a batch containing a single episode.

    Instances are created by retrieving an episode from the buffer when the :class:`Collector` encounters
    `done=True`.
    """

@dataclass(kw_only=True)
class CollectStatsBase(DataclassPPrintMixin):
    """The most basic stats, often used for offline learning."""

    n_collected_episodes: int = 0
    """The number of collected episodes."""
    n_collected_steps: int = 0
    """The number of collected steps."""


@dataclass(kw_only=True)
class CollectStats(CollectStatsBase):
    """A data structure for storing the statistics of rollouts.

    Custom stats collection logic can be implemented by subclassing this class and
    overriding the `update_` methods.

    Ideally, it is instantiated once with correct values and then never modified.
    However, during the collection process instances of modified
    using the `update_` methods. Then the arrays and their corresponding  `_stats` fields
    may become out of sync (we don't update the stats after each update for performance reasons,
    only at the end of the collection). The same for the `collect_time` and `collect_speed`.
    In the `Collector`, :meth:`refresh_sequence_stats` and :meth:`set_collect_time` are
    is called at the end of the collection to update the stats. But for other use cases,
    the users should keep in mind to call this method manually if using the `update_`
    methods.
    """

    collect_time: float = 0.0
    """The time for collecting transitions."""
    collect_speed: float = 0.0
    """The speed of collecting (env_step per second)."""
    returns: np.ndarray = field(default_factory=lambda: np.array([], dtype=float))
    """The collected episode returns."""
    returns_stat: SequenceSummaryStats | None = None
    """Stats of the collected returns."""
    lens: np.ndarray = field(default_factory=lambda: np.array([], dtype=int))
    """The collected episode lengths."""
    lens_stat: SequenceSummaryStats | None = None
    """Stats of the collected episode lengths."""
    pred_dist_std_array: np.ndarray | None = None
    """The standard deviations of the predicted distributions."""
    pred_dist_std_array_stat: dict[int, SequenceSummaryStats] | None = None
    """Stats of the standard deviations of the predicted distributions (maps action dim to stats)"""

    @classmethod
    def with_autogenerated_stats(
        cls,
        returns: np.ndarray,
        lens: np.ndarray,
        n_collected_episodes: int = 0,
        n_collected_steps: int = 0,
        collect_time: float = 0.0,
        collect_speed: float = 0.0,
    ) -> Self:
        """Return a new instance with the stats autogenerated from the given lists."""
        returns_stat = SequenceSummaryStats.from_sequence(returns) if returns.size > 0 else None
        lens_stat = SequenceSummaryStats.from_sequence(lens) if lens.size > 0 else None
        return cls(
            n_collected_episodes=n_collected_episodes,
            n_collected_steps=n_collected_steps,
            collect_time=collect_time,
            collect_speed=collect_speed,
            returns=returns,
            returns_stat=returns_stat,
            lens=np.array(lens, int),
            lens_stat=lens_stat,
        )

    def update_at_step_batch(
        self,
        step_batch: CollectStepBatchProtocol,
        refresh_sequence_stats: bool = False,
    ) -> None:
        self.n_collected_steps += len(step_batch)
        dist = step_batch.dist
        action_std: torch.Tensor | None = None

        if dist is not None:
            action_std = np.atleast_2d(to_numpy(get_stddev_from_dist(dist)))

            if self.pred_dist_std_array is None:
                self.pred_dist_std_array = np.atleast_2d(to_numpy(action_std))
            else:
                self.pred_dist_std_array = np.concatenate(
                    (self.pred_dist_std_array, np.atleast_2d(to_numpy(action_std))),
                )
        if refresh_sequence_stats:
            self.refresh_std_array_stats()

    def update_at_episode_done(
        self,
        episode_batch: EpisodeBatchProtocol,
        # NOTE: in the MARL setting this is not actually a float but rather an array or list, see todo below
        episode_return: float,
        refresh_sequence_stats: bool = False,
    ) -> None:
        self.lens = np.concatenate((self.lens, [len(episode_batch)]), dtype=int)  # type: ignore
        self.n_collected_episodes += 1
        if self.returns.size == 0:
            # TODO: needed for non-1dim arrays returns that happen in the MARL setting
            #   There are multiple places that assume the returns to be 1dim, so this is a hack
            #   Since MARL support is currently not a priority, we should either raise an error or
            #   implement proper support for it. At the moment tests like `test_collector_with_multi_agent` fail
            #   when assuming 1d returns
            self.returns = np.array([episode_return], dtype=float)
        else:
            self.returns = np.concatenate((self.returns, [episode_return]), dtype=float)  # type: ignore
        if refresh_sequence_stats:
            self.refresh_return_stats()
            self.refresh_len_stats()

    def set_collect_time(self, collect_time: float, update_collect_speed: bool = True) -> None:
        if collect_time < 0:
            raise ValueError(f"Collect time should be non-negative, but got {collect_time=}.")

        self.collect_time = collect_time
        if update_collect_speed:
            if collect_time == 0:
                log.error(
                    "Collect time is 0, setting collect speed to 0. Did you make a rounding error?",
                )
                self.collect_speed = 0.0
            else:
                self.collect_speed = self.n_collected_steps / collect_time

    def refresh_return_stats(self) -> None:
        if self.returns.size > 0:
            self.returns_stat = SequenceSummaryStats.from_sequence(self.returns)
        else:
            self.returns_stat = None

    def refresh_len_stats(self) -> None:
        if self.lens.size > 0:
            self.lens_stat = SequenceSummaryStats.from_sequence(self.lens)
        else:
            self.lens_stat = None

    def refresh_std_array_stats(self) -> None:
        if self.pred_dist_std_array is not None and self.pred_dist_std_array.size > 0:
            # need to use .T because action dim supposed to be the first axis in compute_dim_to_summary_stats
            self.pred_dist_std_array_stat = compute_dim_to_summary_stats(self.pred_dist_std_array.T)
        else:
            self.pred_dist_std_array_stat = None

    def refresh_all_sequence_stats(self) -> None:
        self.refresh_return_stats()
        self.refresh_len_stats()
        self.refresh_std_array_stats()
TCollectStats = TypeVar("TCollectStats", bound=CollectStats)

def get_stddev_from_dist(dist: Distribution) -> torch.Tensor:
    """Return the standard deviation of the given distribution.

    Same as `dist.stddev` for all distributions except `Categorical`, where it is computed
    by assuming that the output values 0, ..., K have the corresponding numerical meaning.
    See `here <https://discuss.pytorch.org/t/pytorch-distribution-mean-returns-nan/61978/9>`_
    for a discussion on `stddev` and `mean` of `Categorical`.
    """
    if isinstance(dist, Categorical):
        # torch doesn't implement stddev for Categorical, so we compute it ourselves
        probs = torch.atleast_2d(dist.probs)
        n_actions = probs.shape[-1]
        possible_actions = torch.arange(n_actions, device=dist.probs.device).float()

        mean = torch.sum(probs * possible_actions, dim=1)
        var = torch.sum(probs * (possible_actions - mean.unsqueeze(1)) ** 2, dim=1)
        stddev = torch.sqrt(var)
        if len(dist.batch_shape) == 0:
            return stddev
        return torch.atleast_2d(stddev).T

    return dist.stddev if dist is not None else torch.tensor([])

def _nullable_slice(obj: _TArrLike, indices: np.ndarray) -> _TArrLike:
    """Return None, or the values at the given indices if the object is not None."""
    if obj is not None:
        return obj[indices]  # type: ignore[index, return-value]
    return None  # type: ignore[unreachable]


def _dict_of_arr_to_arr_of_dicts(dict_of_arr: dict[str, np.ndarray | dict]) -> np.ndarray:
    return np.array(Batch(dict_of_arr).to_list_of_dicts())


def _HACKY_create_info_batch(info_array: np.ndarray) -> Batch:
    """TODO: this exists because of multiple bugs in Batch and to restore backwards compatibility.
    Batch should be fixed and this function should be removed asap!.
    """
    if info_array.dtype != np.dtype("O"):
        raise ValueError(
            f"Expected info_array to have dtype=object, but got {info_array.dtype}.",
        )

    truthy_info_indices = info_array.nonzero()[0]
    falsy_info_indices = set(range(len(info_array))) - set(truthy_info_indices)
    falsy_info_indices = np.array(list(falsy_info_indices), dtype=int)

    if len(falsy_info_indices) == len(info_array):
        return Batch()

    some_nonempty_info = None
    for info in info_array:
        if info:
            some_nonempty_info = info
            break

    info_array = copy(info_array)
    info_array[falsy_info_indices] = some_nonempty_info
    result_batch_parent = Batch(info=info_array)
    result_batch_parent.info[falsy_info_indices] = {}
    return result_batch_parent.info





def _patched_compute_action_policy_hidden(
        self,
        random: bool,
        ready_env_ids_R: np.ndarray,
        last_obs_RO: np.ndarray,
        last_info_R: np.ndarray,
        last_hidden_state_RH: np.ndarray | torch.Tensor | Batch | None = None,
) -> CollectActionBatchProtocol:
    """Returns the action, the normalized action, a "policy" entry, and the hidden state."""
    if random:
        try:
            act_normalized_RA = np.array(
                [self._action_space[i].sample() for i in ready_env_ids_R],
            )
        # TODO: test whether envpool env explicitly
        except TypeError:  # envpool's action space is not for per-env
            act_normalized_RA = np.array([self._action_space.sample() for _ in ready_env_ids_R])
        act_RA = self.policy.map_action_inverse(np.array(act_normalized_RA))
        policy_R = Batch()
        hidden_state_RH = None
        # TODO: instead use a (uniform) Distribution instance that corresponds to sampling from action_space
        action_dist_R = None

    else:
        info_batch = _HACKY_create_info_batch(last_info_R)
        obs_batch_R = cast(ObsBatchProtocol, Batch(obs=last_obs_RO, info=info_batch))


        act_batch_RA: ActBatchProtocol | DistBatchProtocol = self.policy(
            obs_batch_R,
            last_hidden_state_RH,
        )

        act_RA = to_numpy(act_batch_RA.act)
        if self.exploration_noise:
            act_RA = self.policy.exploration_noise(act_RA, obs_batch_R)
        act_normalized_RA = self.policy.map_action(act_RA)

        # TODO: cleanup the whole policy in batch thing
        # todo policy_R can also be none, check
        policy_R = act_batch_RA.get("policy", Batch())
        if not isinstance(policy_R, Batch):
            raise RuntimeError(
                f"The policy result should be a {Batch}, but got {type(policy_R)}",
            )

        hidden_state_RH = act_batch_RA.get("state", None)
        # TODO: do we need the conditional? Would be better to just add hidden_state which could be None
        if hidden_state_RH is not None:
            policy_R.hidden_state = (
                hidden_state_RH  # save state into buffer through policy attr
            )
        # can't use act_batch_RA.dist directly as act_batch_RA might not have that attribute
        action_dist_R = act_batch_RA.get("dist")

    return cast(
        CollectActionBatchProtocol,
        Batch(
            act=act_RA,
            act_normalized=act_normalized_RA,
            policy_entry=policy_R,
            dist=action_dist_R,
            hidden_state=hidden_state_RH,
        ),
    )

   # TODO: reduce complexity, remove the noqa
def _patched_collect(  # noqa: C901
    self,
    n_step: int | None = None,
    n_episode: int | None = None,
    random: bool = False,
    render: float | None = None,
    gym_reset_kwargs: dict[str, Any] | None = None,
) -> TCollectStats:
    """This method is currently very complex, but it's difficult to break it down into smaller chunks.

    Please read the block-comment of the class to understand the notation
    in the implementation.

    It does the collection by executing the following logic:

    0. Keep track of n_step and n_episode for being able to stop the collection.
    1.  Create a CollectStats instance to store the statistics of the collection.
    2.  Compute actions (with policy or sampling from action space) for the R currently active envs.
    3.  Perform a step in these R envs.
    4.  Perform on-step hook on the result
    5.  Update the CollectStats (using `update_at_step_batch`) and the internal counters after the step
    6.  Add the resulting R transitions to the buffer
    7.  Find the D envs that reached done in the current iteration
    8.  Reset the envs that reached done
    9.  Extract episodes for the envs that reached done from the buffer
    10. Perform on-episode-done hook. If it has a return, modify the transitions belonging to the episodes inside the buffer inplace
    11. Update the CollectStats instance with the episodes from 9. by using `update_on_episode_done`
    12. Prepare next step in while loop by saving the last observations and infos
    13. Remove S surplus envs from collection mechanism, thereby reducing R to R-S, to increase performance
    14. Update instance-level collection counters (contrary to counters with a lifetime of the collect execution)
    15. Prepare for the next call of collect (save last observations and info to collector state)

    You can search for Step <n> to find where it happens
    """
    # TODO: can't do it init since AsyncCollector is currently a subclass of Collector
    if self.env.is_async:
        raise ValueError(
            f"Please use AsyncCollector for asynchronous environments. "
            f"Env class: {self.env.__class__.__name__}.",
        )

    ready_env_ids_R: np.ndarray[Any, np.dtype[np.signedinteger]]
    """provides a mapping from local indices (indexing within `1, ..., R` where `R` is the number of ready envs)
     to global ones (indexing within `1, ..., num_envs`). So the entry i in this array is the global index of the i-th ready env."""
    if n_step is not None:
        ready_env_ids_R = np.arange(self.env_num)
    elif n_episode is not None:
        if self.env_num > n_episode:
            log.warning(
                f"Number of episodes ({n_episode}) is smaller than the number of environments "
                f"({self.env_num}). This means that {self.env_num - n_episode} "
                f"environments (or, equivalently, parallel workers) will not be used!",
            )
        ready_env_ids_R = np.arange(min(self.env_num, n_episode))
    else:
        raise RuntimeError("Input validation failed, this is a bug and shouldn't have happened")

    if self._pre_collect_obs_RO is None or self._pre_collect_info_R is None:
        raise ValueError(
            "Initial obs and info should not be None. "
            "Either reset the collector (using reset or reset_env) or pass reset_before_collect=True to collect.",
        )

    # Step 0
    # get the first obs to be the current obs in the n_step case as
    # episodes as a new call to collect does not restart trajectories
    # (which we also really don't want)
    step_count = 0
    num_collected_episodes = 0
    episode_returns: list[float] = []
    episode_lens: list[int] = []
    episode_start_indices: list[int] = []

    # Step 1
    collect_stats = self.collect_stats_class()

    # in case we select fewer episodes than envs, we run only some of them
    last_obs_RO = _nullable_slice(self._pre_collect_obs_RO, ready_env_ids_R)
    last_info_R = _nullable_slice(self._pre_collect_info_R, ready_env_ids_R)
    last_hidden_state_RH = _nullable_slice(
        self._pre_collect_hidden_state_RH,
        ready_env_ids_R,
    )

    #CC obs_last and next alignment and debug
    self._last_obs_per_agent = {}
    self._diag_prev_obs = {}  # {agent_id: np.ndarray copy of last obs}
    self._diag_turn = {}

    for i in range(len(ready_env_ids_R)):
        aid0 = last_obs_RO[i]["agent_id"]
        self._diag_prev_obs[aid0] = np.array(last_obs_RO[i]["obs"], copy=True)
        self._diag_turn[aid0] = 0

    self._per_env_agent_done = [dict() for _ in range(self.env_num)]  # per-env dict: agent_id -> bool
    self._roster = [set() for _ in range(self.env_num)]

    self._send_none_next = [False] * self.env_num


    self._dbg_buf_writes = 0
    self._DBG_BUF_CAP = 20

    self._prev_act = {}

    ######################################
    if not hasattr(self, "_dbg_stack"):
            self._dbg_stack = 0
    ######################################

    while True:

        # Step 2
        # CC get the next action and related stats from the previous observation
        collect_action_computation_batch_R = self._compute_action_policy_hidden(
            random=random,
            ready_env_ids_R=ready_env_ids_R,
            last_obs_RO=last_obs_RO,
            last_info_R=last_info_R,
            last_hidden_state_RH=last_hidden_state_RH,
        )
        TraceLogger.log(log, lambda: f"Action: {collect_action_computation_batch_R.act}")

        #CC logic for passing correct action
        for i in range(len(ready_env_ids_R)):
            aid = int(last_obs_RO[i]["agent_id"])
            self._prev_act[aid] = collect_action_computation_batch_R.act_normalized[i]

        # Step 3
        #CC get next obs reward and flags from underlying PettingZoo wrapper
        obs_next_RO, rew_R, terminated_R, truncated_R, info_R = self.env.step(
            collect_action_computation_batch_R.act_normalized,
            ready_env_ids_R,
        )

        #CC individual termination functionality
        done_R = np.zeros_like(terminated_R, dtype=bool)
        for i, env_id in enumerate(ready_env_ids_R):
            eid = int(env_id)
            aid = obs_next_RO[i]["agent_id"]

            self._roster[eid].add(aid)
            self._per_env_agent_done[eid][aid] = bool(terminated_R[i] or truncated_R[i])

            roster = self._roster[eid] if self._roster[eid] else self._per_env_agent_done[eid].keys()
            done_R[i] = all(self._per_env_agent_done[eid].get(a, False) for a in roster)

        #central critic
        if not hasattr(self, "_last_global_per_agent"):
            self._last_global_per_agent = {}

        obs_global_list = []
        obs_global_next_list = []
        last_obs_list = []  # this will become last_obs_RO

        for i in range(len(ready_env_ids_R)):
            aid = obs_next_RO[i]["agent_id"]  # the acting agent this turn
            # fetch that agent’s last stored obs
            last_obs_for_agent = self._last_obs_per_agent.get(aid, obs_next_RO[i])
            # add it to the list
            last_obs_list.append(last_obs_for_agent)
            # update storage
            self._last_obs_per_agent[aid] = obs_next_RO[i]

            ########CCCCCCCCCCCCCCCCCC##############
            #central critic obs alignment
            g_next = info_R[i]["obs_global"]  # global at current time (paired with obs_next)
            g_prev = self._last_global_per_agent.get(aid, g_next)  # fallback first time

            obs_global_list.append(g_prev)
            obs_global_next_list.append(g_next)
            self._last_global_per_agent[aid] = g_next




        #CC replace shared last_obs_RO with our per-agent list
        last_obs_RO = np.asarray(last_obs_list, dtype=object)

        #CC logic for passing correct action
        act_to_use = np.array([
            self._prev_act.pop(int(obs_next_RO[i]["agent_id"]),
                               np.zeros_like(collect_action_computation_batch_R.act_normalized[i]))
            for i in range(len(ready_env_ids_R))
        ], dtype=np.float32)


        # #central CRITIC
        # obs_global_R = np.stack([last_info_R[i]["obs_global"] for i in range(len(last_info_R))], axis=0)
        # obs_global_next_R = np.stack([info_R[i]["obs_global"] for i in range(len(info_R))], axis=0)

        #############CCCCCCCCCCCCC###############
        obs_global_R = np.stack(obs_global_list, axis=0)
        obs_global_next_R = np.stack(obs_global_next_list, axis=0)

        current_step_batch_R = cast(
            CollectStepBatchProtocol,
            Batch(
                obs=last_obs_RO,
                dist=collect_action_computation_batch_R.dist,
                act= act_to_use,
                policy=collect_action_computation_batch_R.policy_entry,
                obs_next=obs_next_RO,
                rew=rew_R,
                terminated=terminated_R,
                truncated=truncated_R,
                done=done_R,
                info=info_R,

                #########CC###############
                obs_global=obs_global_R,
                obs_global_next=obs_global_next_R,
            ),
        )

        # TODO: only makes sense if render_mode is human.
        #  Also, doubtful whether it makes sense at all for true vectorized envs
        if render:
            self.env.render()
            if not np.isclose(render, 0):
                time.sleep(render)

        # Step 4
        self.run_on_step_hook(
            collect_action_computation_batch_R,
            current_step_batch_R,
        )

        # Step 5, collect statistics
        collect_stats.update_at_step_batch(current_step_batch_R)
        num_episodes_done_this_iter = np.sum(done_R)
        num_collected_episodes += num_episodes_done_this_iter
        step_count += len(ready_env_ids_R)


        #CC empties info dict throwing an error
        if "info" in current_step_batch_R:
            current_step_batch_R.info = [{} for _ in range(len(ready_env_ids_R))]

        # Step 6
        # add data into the buffer. Since the buffer is essentially an array, we don't want
        # to add the dist. One should not have arrays of dists but rather a single, batch-wise dist.
        # Tianshou already implements slicing of dists, but we don't yet implement merging multiple
        # dists into one, which would be necessary to make a buffer with dists work properly


        batch_to_add_R = copy(current_step_batch_R)
        batch_to_add_R.pop("dist")
        batch_to_add_R = cast(RolloutBatchProtocol, batch_to_add_R)


        insertion_idx_R, ep_return_R, ep_len_R, ep_start_idx_R = self.buffer.add(
            batch_to_add_R,
            buffer_ids=ready_env_ids_R,
        )

        # preparing for the next iteration
        # obs_next, info and hidden_state will be modified inplace in the code below,
        # so we copy to not affect the data in the buffer
        last_obs_RO = copy(obs_next_RO)
        last_info_R = copy(info_R)
        last_hidden_state_RH = copy(collect_action_computation_batch_R.hidden_state)

        # Preparing last_obs_RO, last_info_R, last_hidden_state_RH for the next while-loop iteration
        # Resetting envs that reached done, or removing some of them from the collection if needed (see below)
        if num_episodes_done_this_iter > 0:
            # TODO: adjust the whole index story, don't use np.where, just slice with boolean arrays
            # D - number of envs that reached done in the rollout above
            # local_idx - see block comment on class level
            # Step 7
            env_done_local_idx_D = np.where(done_R)[0]
            """Indexes which episodes are done within the ready envs, so it can be used for selecting from `..._R` arrays.
            Stands in contrast to the "global" index, which counts within all envs and is unsuitable for selecting from `..._R` arrays."""
            episode_lens_D = ep_len_R[env_done_local_idx_D]
            episode_returns_D = ep_return_R[env_done_local_idx_D]
            episode_start_indices_D = ep_start_idx_R[env_done_local_idx_D]

            episode_lens.extend(episode_lens_D)
            episode_returns.extend(episode_returns_D)
            episode_start_indices.extend(episode_start_indices_D)

            # Step 8
            # now we copy obs_next to obs, but since there might be
            # finished episodes, we have to reset finished envs first.
            gym_reset_kwargs = gym_reset_kwargs or {}
            # The index env_done_idx_D was based on 0, ..., R
            # However, each env has an index in the context of the vectorized env and buffer. So the env 0 being done means
            # that some env of the corresponding "global" index was done. The mapping between "local" index in
            # 0,...,R and this global index is maintained by the ready_env_ids_R array.
            # See the class block comment for more details
            env_done_global_idx_D = ready_env_ids_R[env_done_local_idx_D]
            """Indexes which episodes are done within all envs, i.e., within the index `1, ..., num_envs`. It can be
            used to communicate with the vector env, where env ids are selected from this "global" index.
            Is not suited for selecting from the ready envs (`..._R` arrays), use the local counterpart instead.
            """
            obs_reset_DO, info_reset_D = self.env.reset(
                env_id=env_done_global_idx_D,
                **gym_reset_kwargs,
            )

            # Set the hidden state to zero or None for the envs that reached done
            # TODO: does it have to be so complicated? We should have a single clear type for hidden_state instead of
            #  this complex logic
            self._reset_hidden_state_based_on_type(env_done_local_idx_D, last_hidden_state_RH)

            # Step 9
            # execute episode hooks for those envs which emitted 'done'
            for local_done_idx, cur_ep_return in zip(
                env_done_local_idx_D,
                episode_returns_D,
                strict=True,
            ):
                # retrieve the episode batch from the buffer using the episode start and stop indices
                ep_start_idx, ep_stop_idx = (
                    int(ep_start_idx_R[local_done_idx]),
                    int(insertion_idx_R[local_done_idx] + 1),
                )

                ep_index_array = self.buffer.get_buffer_indices(ep_start_idx, ep_stop_idx)
                ep_batch = cast(EpisodeBatchProtocol, self.buffer[ep_index_array])

                # Step 10
                episode_hook_additions = self.run_on_episode_done(ep_batch)
                if episode_hook_additions is not None:
                    if n_episode is None:
                        raise ValueError(
                            "An on_episode_done_hook with non-empty returns is not supported for n_step collection."
                            "Such hooks should only be used when collecting full episodes. Got a on_episode_done_hook "
                            f"that would add the following fields to the buffer: {list(episode_hook_additions)}.",
                        )

                    for key, episode_addition in episode_hook_additions.items():
                        self.buffer.set_array_at_key(
                            episode_addition,
                            key,
                            index=ep_index_array,
                        )
                        # executing the same logic in the episode-batch since stats computation
                        # may depend on the presence of additional fields
                        ep_batch.set_array_at_key(
                            episode_addition,
                            key,
                        )
                # Step 11
                # Finally, update the stats
                collect_stats.update_at_episode_done(
                    episode_batch=ep_batch,
                    episode_return=cur_ep_return,
                )

            # Step 12
            # preparing for the next iteration
            last_obs_RO[env_done_local_idx_D] = obs_reset_DO
            last_info_R[env_done_local_idx_D] = info_reset_D

            for gid in map(int, env_done_global_idx_D):
                self._per_env_agent_done[gid].clear()
                self._roster[gid].clear()

            # Step 13
            # Handling the case when we have more ready envs than desired and are not done yet
            #
            # This can only happen if we are collecting a fixed number of episodes
            # If we have more ready envs than there are remaining episodes to collect,
            # we will remove some of them for the next rollout
            # One effect of this is the following: only envs that have completed an episode
            # in the last step can ever be removed from the ready envs.
            # Thus, this guarantees that each env will contribute at least one episode to the
            # collected data (the buffer). This effect was previous called "avoiding bias in selecting environments"
            # However, it is not at all clear whether this is actually useful or necessary.
            # Additional naming convention:
            # S - number of surplus envs
            # TODO: can the whole block be removed? If we have too many episodes, we could just strip the last ones.
            #   Changing R to R-S highly increases the complexity of the code.
            if n_episode:
                remaining_episodes_to_collect = n_episode - num_collected_episodes
                surplus_env_num = len(ready_env_ids_R) - remaining_episodes_to_collect
                if surplus_env_num > 0:
                    # R becomes R-S here, preparing for the next iteration in while loop
                    # Everything that was of length R needs to be filtered and become of length R-S.
                    # Note that this won't be the last iteration, as one iteration equals one
                    # step and we still need to collect the remaining episodes to reach the breaking condition.

                    # creating the mask
                    env_to_be_ignored_ind_local_S = env_done_local_idx_D[:surplus_env_num]
                    env_should_remain_R = np.ones_like(ready_env_ids_R, dtype=bool)
                    env_should_remain_R[env_to_be_ignored_ind_local_S] = False
                    # stripping the "idle" indices, shortening the relevant quantities from R to R-S
                    ready_env_ids_R = ready_env_ids_R[env_should_remain_R]
                    last_obs_RO = last_obs_RO[env_should_remain_R]
                    last_info_R = last_info_R[env_should_remain_R]
                    if collect_action_computation_batch_R.hidden_state is not None:
                        last_hidden_state_RH = last_hidden_state_RH[env_should_remain_R]  # type: ignore[index]

        if (n_step and step_count >= n_step) or (
            n_episode and num_collected_episodes >= n_episode
        ):
            break

    # Check if we screwed up somewhere
    if self.raise_on_nan_in_buffer and self.buffer.hasnull():
        nan_batch = self.buffer.isnull().apply_values_transform(np.sum)

        raise MalformedBufferError(
            "NaN detected in the buffer. You can drop them with `buffer.dropnull()`. "
            "This error is most often caused by an incorrect use of `EpisodeRolloutHooks`"
            "together with the `n_steps` (instead of `n_episodes`) option, or by "
            "an incorrect implementation of `StepHook`."
            "Here an overview of the number of NaNs per field: \n"
            f"{nan_batch}",
        )

    # Step 14
    # update instance-lifetime counters, different from collect_stats
    self.collect_step += step_count
    self.collect_episode += num_collected_episodes

    # Step 15
    if n_step:
        # persist for future collect iterations
        self._pre_collect_obs_RO = last_obs_RO
        self._pre_collect_info_R = last_info_R
        self._pre_collect_hidden_state_RH = last_hidden_state_RH
    elif n_episode:
        # reset envs and the _pre_collect fields
        self.reset_env(gym_reset_kwargs)  # todo still necessary?
    return collect_stats