image: $CI_REGISTRY/cps/cps-rl/safe-rl-autodrive/python_image:3.11

stages:
  - static-check
  - install
  - test

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  - poetry config virtualenvs.in-project true

ruff:
  stage: static-check
  script:
    - ruff check --output-format=gitlab .
  allow_failure: true

poetry_install:
  stage: install
  script:
    - apt update
    - apt install swig -y
    - apt install libgmp-dev libcdd-dev -y
    - poetry install --with tests,scripts
#  artifacts:  # Artifact size too large!
#    paths:
#      - .venv

tests:
  stage: test
  script:
    - apt update
    - apt install swig -y
    - apt install libgmp-dev libcdd-dev -y
    - poetry install --with tests
    - poetry run pytest tests
  needs:
    - job: poetry_install
      artifacts: true
