# syntax=docker/dockerfile:1.4
ARG BASE_IMAGE=autodrive-base:latest

FROM ${BASE_IMAGE} as updater

WORKDIR /autodrive

RUN --mount=type=ssh --mount=type=cache,target=$POETRY_CACHE_DIR poetry update


FROM python:3.11-slim as runtime

ENV VIRTUAL_ENV=/autodrive/.venv \
    PATH="/autodrive/.venv/bin:$PATH"

# Install additional project dependencies
RUN apt update && apt upgrade -y && \
    apt install -y \
    software-properties-common \
    build-essential \
    libeigen3-dev \
    libboost-all-dev \
    protobuf-compiler \
    libgmp-dev \
    libspdlog-dev \
    libgl1-mesa-glx

WORKDIR /autodrive

COPY --from=updater ${VIRTUAL_ENV} ${VIRTUAL_ENV}

# Copy project files
COPY examples examples