# syntax=docker/dockerfile:1.4
FROM python:3.11 as builder-base


ENV DEBIAN_FRONTEND=noninteractive \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

RUN apt update && apt upgrade -y && \
    apt install -y \
    software-properties-common \
    build-essential \
    curl \
    git \
    wget \
    nano \
    cmake \
    zlib1g-dev \
    libreadline-dev \
    openssh-server

# Download public key for gitlab
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan gitlab.lrz.de >> ~/.ssh/known_hosts

# Install additional project dependencies
RUN apt update && apt upgrade -y && \
    apt install -y \
    libeigen3-dev \
    libboost-all-dev \
    protobuf-compiler \
    libgmp-dev \
    libspdlog-dev \
    libgl1-mesa-glx

FROM builder-base as py-installed

RUN pip install poetry

WORKDIR /autodrive

# Copy only the dependency files first
COPY pyproject.toml ./

RUN --mount=type=ssh --mount=type=cache,target=$POETRY_CACHE_DIR poetry install --no-root

FROM builder-base as sonia-builder


# Bump cmake version for commonroad cpp environment model
ARG CMAKE_VERSION=3.27.0
RUN wget "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh" \
    -q -O /tmp/cmake-install.sh && \
    chmod u+x /tmp/cmake-install.sh && \
    mkdir /opt/cmake && \
    /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake && \
    rm /tmp/cmake-install.sh
ENV PATH="/opt/cmake/bin:${PATH}"

RUN mkdir -p /wheels

# Clone SONIA repository and install dependencies. Set sonia version to fixed commit.
WORKDIR /external
RUN --mount=type=ssh git clone git@gitlab.lrz.de:cps/sonia.git && \
    cd sonia && \
    git checkout c78fbac67d0a6510f71eb003cec34bdc20e8191e
    
RUN --mount=type=ssh --mount=type=cache,target=/root/.cache/pip \
    cd sonia && \
    CMAKE_ARGS="-DBUILD_COMMONROAD_INT=ON" pip wheel . --no-deps --wheel-dir=/wheels -v

FROM py-installed as sonia-installed

COPY --from=sonia-builder /wheels /wheels

RUN --mount=type=cache,target=/root/.cache/pip \
    . /autodrive/.venv/bin/activate && \
    cd /wheels && \
    WHEEL_FILE=$(ls sonia_*.whl) && \
    pip install "${WHEEL_FILE}[commonroad]"
